export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";

export const GET_LIST_DOCUMENT_REQUEST = "admin/GET_LIST_DOCUMENT_REQUEST";
export const GET_LIST_DOCUMENT_SUCCESS = "admin/GET_LIST_DOCUMENT_SUCCESS";

export const SIGN_GOOGLE_SUCCESS = "SIGN_GOOGLE_SUCCESS";
export const SIGN_GOOGLE_REQUEST = "SIGN_GOOGLE_REQUEST";
export const SIGN_GOOGLE_FAILED = "SIGN_GOOGLE_FAILED";

export const UPLOAD_DOCUMENT_REQUEST = "admin/UPLOAD_DOCUMENT_REQUEST";
export const UPLOAD_DOCUMENT_SUCCESS = "admin/UPLOAD_DOCUMENT_SUCCESS";
export const UPLOAD_DOCUMENT_FAILED = "admin/UPLOAD_DOCUMENT_FAILED";

export const GET_LIST_USER_UNCHECK_REQUEST = "admin/GET_LIST_USER_UNCHECK_REQUEST";
export const GET_LIST_USER_UNCHECK_SUCCESS = "admin/GET_LIST_USER_UNCHECK_SUCCESS";
export const GET_LIST_USER_UNCHECK_FAILED = "admin/GET_LIST_USER_UNCHECK_FAILED";

export const GET_DOCUMENT_BY_ID_REQUEST = "GET_DOCUMENT_BY_ID_REQUEST";
export const GET_DOCUMENT_BY_ID_SUCCESS = "GET_DOCUMENT_BY_ID_SUCCESS";

export const GET_LIST_DOCUMENT_USER_REQUEST = "/user/GET_LIST_DOCUMENT_USER_REQUEST";
export const GET_LIST_DOCUMENT_USER_SUCCESS = "/user/GET_LIST_DOCUMENT_USER_SUCCESS";
export const GET_LIST_DOCUMENT_USER_FAILED = "/user/GET_LIST_DOCUMENT_USER_FAILED";

export const ASSIGN_USER_REQUEST = "/admin/ASSIGN_USER_REQUEST";
export const ASSIGN_USER_SUCCESS = "/admin/ASSIGN_USER_SUCCESS";
export const ASSIGN_USER_FAILED = "/admin/ASSIGN_USER_FAILED";

export const GET_LIST_DELETED_REQUEST = "/admin/GET_LIST_DELETED_REQUEST";
export const GET_LIST_DELETED_SUCCESS = "/admin/GET_LIST_DELETED_SUCCESS";


export const CLEAR_DATA_ADMIN = "/admin/CLEAR_DATA_ADMIN";
export const CLEAR_DATA_USER = "/user/CLEAR_DATA_USER";
